/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GGroupSlugIndexRouteImport } from './routes/g/$groupSlug/index'
import { Route as GGroupSlugShoppingIndexRouteImport } from './routes/g/$groupSlug/shopping/index'
import { Route as GGroupSlugPlannerIndexRouteImport } from './routes/g/$groupSlug/planner/index'
import { Route as GGroupSlugRecipesFinderIndexRouteImport } from './routes/g/$groupSlug/recipes/finder/index'
import { Route as GGroupSlugRSlugIndexRouteImport } from './routes/g/$groupSlug/r/$slug/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupSlugIndexRoute = GGroupSlugIndexRouteImport.update({
  id: '/g/$groupSlug/',
  path: '/g/$groupSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupSlugShoppingIndexRoute = GGroupSlugShoppingIndexRouteImport.update({
  id: '/g/$groupSlug/shopping/',
  path: '/g/$groupSlug/shopping/',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupSlugPlannerIndexRoute = GGroupSlugPlannerIndexRouteImport.update({
  id: '/g/$groupSlug/planner/',
  path: '/g/$groupSlug/planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupSlugRecipesFinderIndexRoute =
  GGroupSlugRecipesFinderIndexRouteImport.update({
    id: '/g/$groupSlug/recipes/finder/',
    path: '/g/$groupSlug/recipes/finder/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GGroupSlugRSlugIndexRoute = GGroupSlugRSlugIndexRouteImport.update({
  id: '/g/$groupSlug/r/$slug/',
  path: '/g/$groupSlug/r/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/g/$groupSlug/': typeof GGroupSlugIndexRoute
  '/g/$groupSlug/planner/': typeof GGroupSlugPlannerIndexRoute
  '/g/$groupSlug/shopping/': typeof GGroupSlugShoppingIndexRoute
  '/g/$groupSlug/r/$slug/': typeof GGroupSlugRSlugIndexRoute
  '/g/$groupSlug/recipes/finder/': typeof GGroupSlugRecipesFinderIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/g/$groupSlug': typeof GGroupSlugIndexRoute
  '/g/$groupSlug/planner': typeof GGroupSlugPlannerIndexRoute
  '/g/$groupSlug/shopping': typeof GGroupSlugShoppingIndexRoute
  '/g/$groupSlug/r/$slug': typeof GGroupSlugRSlugIndexRoute
  '/g/$groupSlug/recipes/finder': typeof GGroupSlugRecipesFinderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/g/$groupSlug/': typeof GGroupSlugIndexRoute
  '/g/$groupSlug/planner/': typeof GGroupSlugPlannerIndexRoute
  '/g/$groupSlug/shopping/': typeof GGroupSlugShoppingIndexRoute
  '/g/$groupSlug/r/$slug/': typeof GGroupSlugRSlugIndexRoute
  '/g/$groupSlug/recipes/finder/': typeof GGroupSlugRecipesFinderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/g/$groupSlug/'
    | '/g/$groupSlug/planner/'
    | '/g/$groupSlug/shopping/'
    | '/g/$groupSlug/r/$slug/'
    | '/g/$groupSlug/recipes/finder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/g/$groupSlug'
    | '/g/$groupSlug/planner'
    | '/g/$groupSlug/shopping'
    | '/g/$groupSlug/r/$slug'
    | '/g/$groupSlug/recipes/finder'
  id:
    | '__root__'
    | '/forgot-password'
    | '/login'
    | '/g/$groupSlug/'
    | '/g/$groupSlug/planner/'
    | '/g/$groupSlug/shopping/'
    | '/g/$groupSlug/r/$slug/'
    | '/g/$groupSlug/recipes/finder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  GGroupSlugIndexRoute: typeof GGroupSlugIndexRoute
  GGroupSlugPlannerIndexRoute: typeof GGroupSlugPlannerIndexRoute
  GGroupSlugShoppingIndexRoute: typeof GGroupSlugShoppingIndexRoute
  GGroupSlugRSlugIndexRoute: typeof GGroupSlugRSlugIndexRoute
  GGroupSlugRecipesFinderIndexRoute: typeof GGroupSlugRecipesFinderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupSlug/': {
      id: '/g/$groupSlug/'
      path: '/g/$groupSlug'
      fullPath: '/g/$groupSlug/'
      preLoaderRoute: typeof GGroupSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupSlug/shopping/': {
      id: '/g/$groupSlug/shopping/'
      path: '/g/$groupSlug/shopping'
      fullPath: '/g/$groupSlug/shopping/'
      preLoaderRoute: typeof GGroupSlugShoppingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupSlug/planner/': {
      id: '/g/$groupSlug/planner/'
      path: '/g/$groupSlug/planner'
      fullPath: '/g/$groupSlug/planner/'
      preLoaderRoute: typeof GGroupSlugPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupSlug/recipes/finder/': {
      id: '/g/$groupSlug/recipes/finder/'
      path: '/g/$groupSlug/recipes/finder'
      fullPath: '/g/$groupSlug/recipes/finder/'
      preLoaderRoute: typeof GGroupSlugRecipesFinderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupSlug/r/$slug/': {
      id: '/g/$groupSlug/r/$slug/'
      path: '/g/$groupSlug/r/$slug'
      fullPath: '/g/$groupSlug/r/$slug/'
      preLoaderRoute: typeof GGroupSlugRSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  GGroupSlugIndexRoute: GGroupSlugIndexRoute,
  GGroupSlugPlannerIndexRoute: GGroupSlugPlannerIndexRoute,
  GGroupSlugShoppingIndexRoute: GGroupSlugShoppingIndexRoute,
  GGroupSlugRSlugIndexRoute: GGroupSlugRSlugIndexRoute,
  GGroupSlugRecipesFinderIndexRoute: GGroupSlugRecipesFinderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
